
project_id = "etlkxmgdmzzysmgkbudx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Configure Edge Functions
[functions]
enabled = true
port = 54324

# Configure Storage
[storage]
enabled = true

[auth]
enabled = true
