// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etlkxmgdmzzysmgkbudx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0bGt4bWdkbXp6eXNtZ2tidWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTIyODEsImV4cCI6MjA2MzUyODI4MX0.z0UPKij58099qadNfp6G5_71SRLzECoeilJ15eoZYt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);